export const CHANGE_SEARCH_TERM = "CHANGE_SEARCH_TERM";
export const FETCH_STARTED = "FETCH_STARTED";
export const FETCH_COMPLETED = "FETCH_COMPLETED";
export const FETCH_FAILED = "FETCH_FAILED";
export const FETCH_TOPTRACK_STARTED = "FETCH_TOPTRACK_STARTED";
export const FETCH_TOPTRACK_COMPLETED = "FETCH_TOPTRACK_COMPLETED";
export const FETCH_TOPTRACK_FAILED = "FETCH_TOPTRACK_FAILED";
